project:
  type: book

book:
  title: "Dominando Agentes de IA"
  author: "William Oliveira"
  date: ""
  chapters:
    - index.qmd
    - chapters/00-visao-geral.qmd
    - chapters/01-intro.qmd
    - chapters/99-references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt
